[project]
name = "python-uv-template"
version = "0.0.1"
description = "Template for python projects managed by uv"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = ["pre-commit>=4.1.0"]


[tool.pyright]
venvPath = "."
venv = ".venv"
